version: '3.6'

services:
  age_of_api:
    container_name: age_of_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - default
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ${SHARED_DIR}:/src/static/uploads/
      - ./migrations:/migrations
    command: "/bin/sh boot.sh"
    depends_on:
      - age_of_db
    links:
      - age_of_db

  age_of_db:
    container_name: age_of_db
    env_file: .env
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    shm_size: 1g
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "max_parallel_workers=32"
      - "-c"
      - "max_parallel_workers_per_gather=8"
      - "-c"
      - "shared_buffers=4096MB"

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command:
      - redis-server

  worker:
    build:
      context: .
      dockerfile: age_of_gold_worker/Dockerfile_worker
    user: celery
    env_file: age_of_gold_worker/.env
    networks:
      - default
    restart: always
    volumes:
      - ${SHARED_DIR}:/src/static/uploads/
    depends_on:
      - redis
      - age_of_db
    command: "celery -A age_of_gold_worker.age_of_gold_worker.tasks worker -l info"

  cron_worker:
    build:
      context: .
      dockerfile: age_of_gold_cron/Dockerfile_cron
    env_file: age_of_gold_cron/.env
    networks:
      - default
    restart: always
    depends_on:
      - redis
      - age_of_db
    command: "sh -c 'sleep 20 && python main_cron.py'"
