apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: <namespace>
type: Opaque
data:
  POSTGRES_USER: PHVzZXI+               # base64 encoded (<user>)
  POSTGRES_PASSWORD: PHBhc3N3b3JkPg==   # base64 encoded (<password>)
  POSTGRES_DB: PGRhdGFiYXNlX25hbWU+     # base64 encoded (<database_name>)
