apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: <namespace>
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      namespace: <namespace>
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: <docker_hub_name>/<worker_image_name>:<tag>
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "1000m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /src/static/uploads
              name: postgres-data
          envFrom:
            - secretRef:
                name: fastapi-secret
          env:
            - name: REDIS_URL
              value: <redis_url>
            - name: REDIS_PORT
              value: <redis_port>
            - name: BASE_URL
              value: <base_url>
            - name: FRONTEND_URL
              value: <frontend_url>
            - name: SMTP_PASSWORD
              value: <smtp_password>
            - name: SMTP_ACCOUNT
              value: <smtp_account>
            - name: SMTP_USER
              value: <smtp_user>
            - name: SMTP_HOST
              value: <smtp_host>
            - name: SMTP_PORT
              value: <smtp_port>
            - name: SMTP_PASSWORD
              value: "<smtp_password>"
            - name: SMTP_ACCOUNT
              value: "<smtp_account>"
            - name: SMTP_USER
              value: "<smtp_user>"
            - name: SMTP_HOST
              value: "<smtp_host>"
            - name: SMTP_PORT
              value: "<smtp_port>"
            - name: S3_ENDPOINT
              value: "<s3_endpoint>"
            - name: S3_ACCESS_KEY
              value: "<s3_access_key>"
            - name: S3_SECRET_KEY
              value: "<s3_secret_key>"
            - name: S3_BUCKET_NAME
              value: "<s3_bucket_name>"
            - name: S3_SECURE
              value: "<s3_secure>"
            - name: S3_ENCRYPTION_KEY
              value: "<s3_encryption_key>"
            - name: PROJECT_NAME
              value: "<project_name>"
          args:
            - celery
            - -A
            - age_of_gold_worker.age_of_gold_worker.tasks
            - worker
            - -l
            - info
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: local-age-of-gold-pvc
